### ISSUE TITLE
MCMT causing mobs to have twins

### ISSUE THREAD

**Issue by Copernicle** [jediminer543/JMT-MCMT#112]
When MCMT is included in the mod list, and when you breed two animals together, two babies are spawned.

**Comment by lele92007** [comment]
could you explain more precisely how this happend for us to be able to reproduce the bug ?
we need the mod list with the version and configs

**Comment by Copernicle** [comment]
**Mod List:**

1. AdLods-1.16.4-4.1.2.0-build.0027
2. mods/BiomesOPlenty-1.16.5-13.1.0.480-universal
3. buildersaddition-1.16.3-20201028b
4. cc-tweaked-1.16.4-1.94.0
5. cloth-config-4.14.54-forge
6. configured-1.5.1-1.16.5.jar
7. CosmeticArmorReworked-1.16.4-v1.jar
8. createaddition-1.16.5-20220129a.jar
9. create-mc1.16.5_v0.3.2g.jar
10. DynamicSurroundings-1.16.5-4.0.5.0.jar
11. FastLeafDecay-v25.2.jar
12. flywheel-1.16-0.2.5.jar
13. ForgeEndertech-1.16.4-7.0.8.0-build.0028.jar
14. globalxp-1.16.5-v1.9.jar
15. Hwyla-forge-1.10.11-B78_1.16.2.jar
16. industrial-foregoing-1.16.5-3.2.14.6-14.jar
17. inventoryprofiles-forge-1.16.2-0.4.2.jar
18. ironchest-1.16.4-11.2.10.jar
19. jei-1.16.5-7.7.1.145.jar
20. JEIEnchantmentInfo-1.16.4-1.2.1.jar
21. kotlinforforge-1.15.1-obf.jar
22. Lollipop-1.16.5-3.2.9.jar
23. lumberjack-2.1.4.jar
24. Mantle-1.16.5-1.6.157.jar
25. mcw-bridges-1.0.4-mc1.16.4.jar
26. mcw-doors-1.0.1fix-mc1.16.4.jar
27. mcw-fences-1.0.2-mc1.16.5.jar
28. mcw-furniture-2.0.1-mc1.16.5.jar
29. mcw-paintings-1.0.2-mc1.16.5.jar
30. mcws-roofs-2.0.0-mc1.16.4.jar
31. mcw-trapdors-1.0.0-mc1.16.4.jar
32. mcw-windows-1.0.2-mc1.16.4.jar
33. MyServerIsCompatible-1.16.5-1.0.jar
34. OptiFine_1.16.5_HD_U_G8.jar
35. pamhc2crops-1.16.3-1.0.1.jar
36. pamhc2foodcore-1.16.3-1.0.0.jar
37. pamhc2foodextended-1.16.3-1.0.4.jar
38. pamhc2trees-1.16.3-1.0.0.jar
39. Powah-1.16.5-2.3.16.jar
40. randompatches-2.4.4-forge.jar
41. repurposed_structures_forge-3.4.6+1.16.5.jar
42. shutupexperimentalsettings-1.0.3.jar
43. sleeping_bags-1.16.4-1.0.1.jar
44. TConstruct-1.16.5-3.3.3.332.jar
45. titanium-1.16.5-3.2.8.7-22.jar
46. travellersboots-1.16.x-1.4.3.jar
47. twilightforest-1.16.5-4.0.870-universal.jar
48. Uppers-0.3.2.jar
49. worldedit-forge-mc1.16.3-7.2.2-dist.jar
50. Xaeros_Minimap_22.1.2_Forge_1.16.5.jar

**Version:** 1.16.5 forge 36.2.26
**Config:** Default

_Note: If you need the files, this is a modpack called AXT made by me._
