### ISSUE TITLE
Lose the ability to break blocks occasionally until server restart

### ISSUE THREAD

**Issue by BBBosp** [jediminer543/JMT-MCMT#14]
Occasionally the world updating breaks in a way that animals no longer breed and blocks can no longer be broken. Seems a lot like being ticks behind and getting block lag, but it does not report so in the log. instead the log gets spammed with 

[14Sep2020 19:21:33.466] [ForkJoinPool-3-worker-5/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException

until it is rebooted. I'm running what was the latest version of your mod until yesterday. I have updtaed to the new version to try it out now as well, but have restore points and can revert. 

Running the server on a MineOS Turnkey Linux VM with 6 cores / 8GB RAM 50GB storage. 
I have the following mods installed
    jmt_mcmt-1.15.2-0.15.39.jar
    Craftable-Saddles-Mod-1.15.2.jar
    Decorative-Blocks-Mod-1.15.2.jar
    Extended-Lights-Mod-1.15.2.jar
    GeneticAnimals-0_5_4.jar
    More+Dogs+1.15.2-1.0.6.jar
    Morpheus-1.15.2-4.2.50.jar
    MrCrayFishs-Furniture-1.15.2.jar
    QuickLeafDecay-MC1.15.2-1.2.5.jar
    astikorcarts-1.15.2-1.0.4.jar
    environmentalcreepers-forge-1.15.2-1.6.1.jar
    horse_colors-1.15.2-1.4.0.jar
    horse_tack-2.1-1.15.2.jar

This mod list has been stable for a few weeks, but struggled due to being bound by single core performance. With your mod installed it runs very well and never falls behind, aside from this hangup. I can provide more detailed logs as needed. If you have any insight it would be fantastic. 

On a side note there may be a conflict with horse_colors-1.15.2-1.4.0.jar that results in horses always having twins? have not fully diagnosed yet.

**Comment by jediminer543** [comment]
Hi, The loss of ability to place blocks means the server is basicly locking up, due to something being in error state

Can you provide some logs to make debugging easier as trying to diagnose these things is somewhat hard

Preferably debug.log

Fingers crossed it's just an fastutil collection missbehaving and I can var-replace it out of existence in a 5 min

**Comment by jediminer543** [comment]
Am, derp, ignore issue close

I pressed the wrong button

Sorry

**Comment by BBBosp** [comment]
So my lates debug.logs should be attached. I attached more than just the latest becasue It may be in number 2 or 3, as I have restarted the server to get it running again. 

regular logs are also available if debug log doesn't cut it. 


[debug.log](https://github.com/jediminer543/JMT-MCMT/files/5220826/debug.log)
[debug-1.log.gz](https://github.com/jediminer543/JMT-MCMT/files/5220828/debug-1.log.gz)
[debug-2.log.gz](https://github.com/jediminer543/JMT-MCMT/files/5220829/debug-2.log.gz)
[debug-3.log.gz](https://github.com/jediminer543/JMT-MCMT/files/5220830/debug-3.log.gz)
[debug-4.log.gz](https://github.com/jediminer543/JMT-MCMT/files/5220831/debug-4.log.gz)
[debug-5.log.gz](https://github.com/jediminer543/JMT-MCMT/files/5220832/debug-5.log.gz)

**Comment by jediminer543** [comment]
Thanks for the logs

debug.log contains everything the normal one does, it just shows all messages down to debug level rather than just info level

Ok so there are probably multiple bugs here; 

The main one to fix is this one, the java.lang.ArrayIndexOutOfBoundsException:
```
[14Sep2020 19:05:26.122] [ForkJoinPool-3-worker-4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.ArrayIndexOutOfBoundsException: -1
[14Sep2020 19:05:26.123] [ForkJoinPool-3-worker-4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet.firstLong(LongLinkedOpenHashSet.java:747)
[14Sep2020 19:05:26.123] [ForkJoinPool-3-worker-4/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.chunk.storage.RegionSectionCache.func_219115_a(SourceFile:60)
...
```

And theres another; an NPE from modded code:
[14Sep2020 19:34:03.264] [ForkJoinPool-3-worker-5/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[14Sep2020 19:34:03.265] [ForkJoinPool-3-worker-5/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraftforge.common.util.LazyOptional.orElseGet(LazyOptional.java:237)
[14Sep2020 19:34:03.265] [ForkJoinPool-3-worker-5/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at mokiyoki.enhancedanimals.ai.ECRoost.func_75250_a(ECRoost.java:26)
...
```

The first one is probably the one that is causing the server to fully lock up; the latter SHOULD just be causing certain mobs to stop working. I'll fix the first one as part of this issue and the other as part of the other issue.

I thought I'd already fixed the first one, but apparently not; so I'll add it to the hit list

**Comment by BBBosp** [comment]
Sounds good. I was running jmt_mcmt-1.15.2-0.15.39.jar until today, so if you fixed it in the latest released yesterday These happened on the old version.

**Comment by jediminer543** [comment]
Try the 0.16.50 build as that may fix it

As I said, I thought I'd already fixed it already so that would explain it

**Comment by BBBosp** [comment]
So to give you an update, 1 week of running consistently with up to 8 players at a time in some instances and the first bug has not returned. 

It looks like the second one that you mentioned should only effect a single mob still occurs sometimes, as well as the log gets hit with  the following line every 2 - 3 minutes, which seems excessive. 

[20Sep2020 20:34:57.729] [MCMT Stats Thread/WARN] [MCMT Dev Warning/]: MCMT is enabled; error logs are invalid for any other mods

Aside from those small things it seems to run well and performance has been exceptional.

**Comment by jediminer543** [comment]
Yeah, I need to put it on an exponential drop off

The goal is to ensure other mod authors don't have to deal with bug reports saying "something broke" when it's not their fault

**Comment by jediminer543** [comment]
As the original issue was solved, and I've added an exp dropoff I'm closing this issue

I'll open another issue for adding the exp dropoff to the config
