### ISSUE TITLE
[1.18.2] world doesn't loads while using MCMT

### ISSUE THREAD

**Issue by CACOKKOTA** [jediminer543/JMT-MCMT#142]
Don't know why, but i'll just leave log here
W/O config settings for compatibility:

[latest.log](https://github.com/jediminer543/JMT-MCMT/files/11558236/latest.log)

With compatibility settings:

[latest.log](https://github.com/jediminer543/JMT-MCMT/files/11558322/latest.log)

**Comment by vladdeda** [comment]
Isn't the 1.18 for 1.18.1? If so wouldn't it make sense that 1.18.2 doesn't load?
