### ISSUE TITLE
Add 1.16.3 Support

### ISSUE THREAD

**Issue by James76931** [jediminer543/JMT-MCMT#19]
Hi.

At the moment, the mod does not support Minecraft 1.16.3. Please could you add support for this?

Thanks!

**Comment by jediminer543** [comment]
Hi, it technically does; I just havent bundled a release yet as Uni stuff is busy and I'm working on removing the problem that is fast util

The 1.16.2 build should work just fine with 1.16.3, though on servers it might get angry and say "there is a version missmatch" becasue forge only does version checking on servers for some reason

**Comment by jediminer543** [comment]
Mostly tested 1.16.3 builds are now live on both github and curseforge for version 0.17.52
