### ISSUE TITLE
[1.16.3] Syncfu question

### ISSUE THREAD

**Issue by YOYOK9** [jediminer543/JMT-MCMT#24]
This is just a question: is the syncfu.jar available for the 1.16.3 version? If so where would the download happen to be? Would defiantly like to give this mod a try, but would prefer to have both if it helps with stability.

**Comment by PaintNinja** [comment]
The syncfu jar for 1.15 works on 1.16.x, while I'm not certain, I think the dev simply forgot to link to it on the 1.16 downloads.
https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading/files/3070849

**Comment by jediminer543** [comment]
Hi, This was due to a bug in curseforge

Since the SyncFu jar is versionless, Curseforge said "you can't upload the same file 3 times

This has been fixed with 0.18.60 which bundles SyncFu and the base mod together
