### ISSUE TITLE
not compatible with Mohist

### ISSUE THREAD

**Issue by Ytoblo** [jediminer543/JMT-MCMT#25]
I think the mohist core is more progressive in terms of 1.16, I already reported this bug to the Mohist team
[latest.log](https://github.com/jediminer543/JMT-MCMT/files/5397488/latest.log)
[debug.log](https://github.com/jediminer543/JMT-MCMT/files/5397489/debug.log)

**Comment by jediminer543** [comment]
Oh

I know what's causing this, you should close the bug with the Mohist team

This is because I am being cheap and replacing an entire variable type rather than actually properly extending the base type

Target: `field_147490_S` - `blockEventQueue`

**Comment by Ytoblo** [comment]
> Oh
> 
> I know what's causing this, you should close the bug with the Mohist team
> 
> This is because I am being cheap and replacing an entire variable type rather than actually properly extending the base type
> 
> Target: `field_147490_S` - `blockEventQueue`

Ok

**Comment by Mgazul** [comment]
Request to close this issue, fixed
