### ISSUE TITLE
Need to talk with U jediminer543

### ISSUE THREAD

**Issue by KubiRem** [jediminer543/JMT-MCMT#27]
Hi @jediminer543 , I want to talk to you privately. My English is not great therefore we will write. I want to open the server with this wonderful mod and want to know more.

That's my discord id KubiRemPL#6064
I would be so thankful.
It would be soo cool to make a large server cuz this mod give ability to do this.

**Comment by jediminer543** [comment]
Poked

**Comment by squidoodly** [comment]
Hello.

I didn't know whether to open a new issue or just use this one so I decided to just use this one.

Was wondering if you could help me understand what is going on here. I've been looking at the code for a little while and tried to do some debugging but I still can't figure out where to start with reverse engineering this mod.

Would appreciate if you could message me (squidoodly#1967) and explain this to me in more detail.

Thanks in advance.

**Comment by KubiRem** [comment]
Hi @squidoodly
Can I know in what context You want to do "reverse engineering" . Do You want to backport this mod or something or just do Your own implementation of this awsome mod???
