### ISSUE TITLE
Discord Server

### ISSUE THREAD

**Issue by squidoodly** [jediminer543/JMT-MCMT#36]
Hello

I am very interested in learning more about this project and how it works however, I cannot find a link to a Discord server nor a Discord handle to message you on.

Was wondering if you are planning on making a Discord server for this project and if not then to message me (squidoodly#1967) so I can ask about it privately.

If you are planning on making a Discord server I would appreciate if you could send me an invite either here or through DMs.

Thank you.

**Comment by NXTler** [comment]
Well he was working on one for mod testing and problaly for the other stuff too but as he wrote in Issue #35 "but I kinda collapsed due to mental health issues" and then he said he would try to finish it when I'm intrested. What is currently going on or if he works on it I dont know.

**Comment by KubiRem** [comment]
Discord server is planned but no ETA or anything.
