### ISSUE TITLE
Testing in 1.16.4

### ISSUE THREAD

**Issue by PenumbraStar** [jediminer543/JMT-MCMT#40]
I run about 175 mods in 1.16.4. After quite a bit of testing I actually noticed slowdowns, specifically with rendering. I know that the mod was intended to be used server side. However I am trying to test exactly how many mods I can use so that I know what type of server I will need. As you said on curse, an option to limit the number of cpu cores or threads would be amazing to use.
Contained below is the logs that repeated for as long as I remained loaded into a world. I tested by loading into multiple works and noticed the same issue. I am sorry I could not post more specifics, however I need to head to sleep for work, so if you need more specifics I can drop them for you. Still, amazing TPS impact, I look forward to seeing more use of this mod in the future!

```
[23:15:17] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
[23:15:17] [ForkJoinPool-3-worker-8/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[23:15:17] [ForkJoinPool-3-worker-5/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
```

**Comment by KubiRem** [comment]
Hi @PenumbraStar !!!
There is actually option to limit threads used by MCMT. It's named "timeoutCount" and it's default to -1 (all cores). 
Please note that you should not set it higer than amount cores on your system.
You should also note that this mod is very helpful for servers, but it's not needed for clients to join this server (and will not help client at all if he would join with MCMT).
Can you share debug.log if you will have a while. Thanks in advance.

Best Regards
Kubi

**Comment by PenumbraStar** [comment]
Ah I completely missed that setting when looking through the config earlier, I'll test it later tonight. I'll share the new debug log when I do so. Thank you for the help!

**Comment by KubiRem** [comment]
No problem I am always willing to help anyone!!!

**Comment by jediminer543** [comment]
Just a note on this: it should not have been named timeout count and this has been changed in the latest release, so you may need to update your config

Other than that I'm closing this issue, if you have any debug logs you want to add please feel free to re-open this issue
