### ISSUE TITLE
Problems in 1.16.4

### ISSUE THREAD

**Issue by NXTler** [jediminer543/JMT-MCMT#43]
I tested MCMT in the newest version of forge 1.16.4 and run into some problems. During World gen it puts out error about it could not save the chnk it generated but the server and the world seemed to be fine. At some point the server just crashed without me doing anything. I didnt had any other mods installed.
Here are the errors:
[Chunk Error 1.16.4.txt](https://github.com/jediminer543/JMT-MCMT/files/5824774/Chunk.Error.1.16.4.txt)
[crash-2021-01-16_17.33.12-server.txt](https://github.com/jediminer543/JMT-MCMT/files/5824775/crash-2021-01-16_17.33.12-server.txt)
The server Ram has also some Spikes? while world gen.. It gets around 4Gb but then resets to about 500Mb.
![Ram Spikes](https://user-images.githubusercontent.com/73062438/104818030-3d468c80-5825-11eb-964c-c5685b0bea5c.PNG)

**Comment by NXTler** [comment]
Litlle update...
I tried out different version of MCMT and Forge but still the same problems.
Maybe a problem with linux or java?
I have to stop any mod testing for now in 1.16.X, its just to unstable to do anything.

**Comment by KubiRemPL** [comment]
> Litlle update...
> I tried out different version of MCMT and Forge but still the same problems.
> Maybe a problem with linux or java?
> I have to stop any mod testing for now in 1.16.X, its just to unstable to do anything.

I mean I have not found any game breaking issues in 1.16. It's working very stable and fine for me. Are you testing only ATM6 or does it happen with other mods?

**Comment by jediminer543** [comment]
@NXTler try running java --version (or -version if that fails) and see what it says

It's possible that MCMT may have issues wit a specific JVM

**Comment by NXTler** [comment]
@KubiRemPL I dont even know what ATM6 is, I just test mods that I really like or are really popular.

**Comment by NXTler** [comment]
![this](https://user-images.githubusercontent.com/73062438/114317778-01605200-9b0a-11eb-9d04-d0f403a80d22.PNG)
@jediminer543 This comes up. Its just that version Linux Mint gave me when I upgraded to the newest version.

**Comment by jediminer543** [comment]
Oki, I'll try spinning up a test VM and see if I can figure out what's wrong

Also, pre-releases are now up on the newly opened discord if you want to try one of them instead (They're being built by github actions)

**Comment by jediminer543** [comment]
Also, try running with JRE 8 and see if that makes a difference; there have been a few cases wherein JRE version has mattered for some reason

**Comment by NXTler** [comment]
@jediminer543 IT WORKED!
I installed JRE 8 and ran the server with it. I dont get any errors now but the weird ram spikes are still there, maybe just a minecraft thing after all? I will start proper mod testing soon and maybe have a look at pre-relaeses.
