### ISSUE TITLE
ATM6 chunk gen crash. was working fine.

### ISSUE THREAD

**Issue by codydbgt** [jediminer543/JMT-MCMT#44]
i thought i would give this mod a shot if used tick threading before im used to crashes and unstable with this type of work thus i will post the logs in the hope of a fix.

[crash-2021-01-16_23.11.14-server.txt](https://github.com/jediminer543/JMT-MCMT/files/5825295/crash-2021-01-16_23.11.14-server.txt)
[2021-01-16-2.log](https://github.com/jediminer543/JMT-MCMT/files/5825297/2021-01-16-2.log)

**Comment by NXTler** [comment]
MCMT is not 100% compatiple with other mods and cause many issues. I will look at this again when I get to 1.16.4 mod testing.
Also MCMT could have some problems with 1.16.4 on its own as I recently discovert in #43.

**Comment by codydbgt** [comment]
this was caused by a players dat file as i found out removing it fixed the issue i can continue testing for you <3
