### ISSUE TITLE
Problems with 1.16.5

### ISSUE THREAD

**Issue by TimyStream** [jediminer543/JMT-MCMT#46]
Hey, when we used this mod on our ATM 6 - 1.16.5 Server, on every Player there spawned about 200 Fish or other mobs and that is not funny :(

**Comment by NXTler** [comment]
MCMT is definitely not 100% compatiple with other mods and cause many issues in combination. In Issue #44 he used ATM 6 too and did not had that Isue so it may be just config thing.

**Comment by KubiRemPL** [comment]
> Hey, when we used this mod on our ATM 6 - 1.16.5 Server, on every Player there spawned about 200 Fish or other mobs and that is not funny :(

Can you disable world threading and see if that helps?

**Comment by codydbgt** [comment]
no i did i used the incontroll mod i didnt think it was this mods fault thoe? not shure?

**Comment by jediminer543** [comment]
Can you provide logs please or add some other detail, as I cant do much with the provided detail
