### ISSUE TITLE
Not working with Lost Cities

### ISSUE THREAD

**Issue by CreepyChicken** [jediminer543/JMT-MCMT#51]
The Cities did not generate, but after I removed only this mod the Generation worked perfectly.

**Comment by NXTler** [comment]
I will add it to the mod testing just need to know in which version you try it

**Comment by NXTler** [comment]
@CreepyChicken I just got the same result as you.
If you want to see the results look up here: https://trello.com/b/xTk6aSYa

**Comment by jediminer543** [comment]
What is broken here? I installed the Lost Cities and enabled it in advanced world options and well...

![2021-04-13_19 36 48](https://user-images.githubusercontent.com/6341928/114603435-9f315980-9c8f-11eb-90f3-8a0fb06d847f.png)

**Comment by NXTler** [comment]
@jediminer543 thats interesting on my server I couldnt get it to run maybe I am dumb...

**Comment by NXTler** [comment]
@jediminer543 Okay Its just a bit tricky to set up on the server side but it works fine now
