### ISSUE TITLE
(Config & Documentation) Setting to blacklist certain threads of the CPU

### ISSUE THREAD

**Issue by Mjrlun** [jediminer543/JMT-MCMT#59]
This would be especially useful for how optifine likes to use the 6th core (on a Ryzen 5 3600) specifically (from top-left to bottom-right, see image) for rendering.*
Elsewise, better documentation within the config file would be useful, because the use of core as opposed to thread is used interchangeably (which is not correct). A core will equal one thread, if the CPU is not multithreaded. However, if this is the case, 1 core = 2 threads.

*(only applies to the r5 3600 to my knowledge, mileage might vary)
![image_2021-05-15_180057](https://user-images.githubusercontent.com/84252662/118380494-c7bab500-b5a7-11eb-86ae-c201e27d8343.png)

**Comment by Titaniumtown** [comment]
Doesn't the OS handle what cores threads run on...?

**Comment by KubiRemPL** [comment]
What CPU is used etc is handled by OS itself. It is better to stay that way. The thing you can do is decrease threads used by MCMT in config if you really need it.

**Comment by Mjrlun** [comment]
If you read my suggestion, I'm asking the ability to blacklist certain CPU threads because of this issue. I asked nothing more.

**Comment by Titaniumtown** [comment]
Yea, but that's not how that works.

**Comment by jediminer543** [comment]
I'm sorry but this is not possible to implement as there is no JVM wide standard that would let me perform thread pinning/process affining/etc,

My advice would be to edit the mod settings to be to 
```toml
paraMaxMode = "Reduction"
paraMax = 1
```

That will always leave a thread free which will make sure the render thread can always schedule itself. I can also try and add a thing that will try to increase the priority of the render thread.
