### ISSUE TITLE
lucky77 causes crashes

### ISSUE THREAD

**Issue by retroheim** [jediminer543/JMT-MCMT#61]
I have a massive modpack that was incompatible with this mod, I managed to sift through all 250 mods, and I found out that the core mod lucky77 is most likely incompatible. As it started working in the batch of mod sifting that it was in, where I removed it since it was a remnant of when I had the casinocraft mod.

**Comment by NXTler** [comment]
Can you send the crash logs and with wich version of mcmt did you try it?

**Comment by retroheim** [comment]
[crash-2021-05-29_20.40.29-server.txt](https://github.com/jediminer543/JMT-MCMT/files/6566531/crash-2021-05-29_20.40.29-server.txt)
so yeah turns out that even after I removed lucky77, it is still crashing but instead of on load, the server crashes when someone joins instead.

I can send that crash report too, if need be.

**Comment by KubiRemPL** [comment]
Could you try remove perfomant?

**Comment by retroheim** [comment]
I don't think I sent the correct crash report. I got one from the recycle bin, sorry. It should not have had performant inside of it.

**Comment by retroheim** [comment]
welp. sorry for the false positive, I re-added lucky77 and it did not crash it again, I still get an issue where it crashes when joining, but that's not related to this issue. Sorry for the trouble. I guess I mistook a different mod I had removed for lucky77 sorry for the trouble! I will create a separate issue for that one though.
