### ISSUE TITLE
Golem Farm: golems stop spawning 

### ISSUE THREAD

**Issue by desuplan** [jediminer543/JMT-MCMT#64]
Unfortunately I can’t pinpoint why to point you in the correct direction. I have a working iron farm, for some reason or other when the server has MCMT installed golems will only spawn three or four times after starting the server. All works fine without MCMT. 

Mods: biomes o plenty, jei/jer(tried removing these and no change) 

Let me know if there’s anything I can do to help figure it out

**Comment by jediminer543** [comment]
Ok, is this just a vanilla standard iron golem spawner

Any design specifics?

I'll try spinning one up

Also sorry for response delay I was doing exams and being depressed (now I'm just being depressed)

**Comment by desuplan** [comment]
The design is one followed on this vid by logic geek https://youtu.be/6EOCDu0r-h8

**Comment by jediminer543** [comment]
Ok, I tried a generic iron golem spawner:

- Create spawning platform `/fill ~-10 ~ ~-10 ~10 ~ ~10 minecraft:netherite_block replace`
- Go down 3 blocks and place beds and villagers
- Set time to night so the sleep
- place a platform seperated by a distance and put a zombie on it
- Wait for golems to spawn

The only issue I can see is that more than 1 golem can spawn at once

Which seems like it would help TBH

I'll try the design in the video later

**Comment by desuplan** [comment]
Tested with the latest release 0.21.80 and can confirm it is now working perfectly. One of the fixes between the last forge release 0.20.75 and 0.21.80 has resolved the issue. Thx for the releases and work your a legend.

**Comment by jediminer543** [comment]
We love to see it when a bug gets fixed and I have no idea why

But it's good to see it's working properly again
