### ISSUE TITLE
There will be 1.12.2 or not???

### ISSUE THREAD

**Issue by KubiRem** [jediminer543/JMT-MCMT#7]
Hello I am modpack maker and for me only thing that matters is performance and stability. 1.15.2 fps are much worse than 1.12.2 btw. I am just wanna know is there will be 100% 1.12.2 port or is this questionable.
I am know this was asked before.

Best Regards KubiRemPL

**Comment by jediminer543** [comment]
Hi,

As discussed in issue #2 the main issue with backporting is that a LOT of stuff changed between 1.12.2 and 1.15/16. While it is on my todo list; I don't have infinite time, and am still finding bugs in the 1.15/16 versions of the mod. (Note I'm bundling 1.15/1.16 together as they are similar in all but like 2 ways so it's not an issue)

However I am trying to get around to doing backporting it; It's just an issue of making sure the current build is sufficiently stable (as trying to fix the same bug twice in two different ways (as that's the issue with backporting) will be a pain); as well as time (as I do have other things I need to do too)

**Comment by WolfBV** [comment]
Consider https://legacy.curseforge.com/minecraft/mc-mods/multithreaded-noise
