### ISSUE TITLE
crash on atm6 server

### ISSUE THREAD

**Issue by gamingouchs** [jediminer543/JMT-MCMT#70]
no idea we were both in base just going through our chest 

https://pastebin.com/vykTjpp7

**Comment by Naheulf** [comment]
Did you read the cursforge mod page https://www.curseforge.com/minecraft/mc-mods/mcmt-multithreading ?
> Known mod incompatibilities
>    Requires configuration changes
> - Clumps - Toggle the option `disableWorldPostTick = true` in the MCMT config

**Comment by jediminer543** [comment]
Am closing as that is a configuration issue

Please re-open or create a new issue if/when more crashes occur post fixing

**Comment by Nikouw36** [comment]
I tried that command but crashes again after 5 minutes of starting the server

Crashlog:
https://pastebin.com/1aCxhzuC
