### ISSUE TITLE
minecraft crashes on world creation

### ISSUE THREAD

**Issue by benjiyk** [jediminer543/JMT-MCMT#76]
Minecraft version- 1.16.5

mods installed- just this one

java version 1.8.0_301

**Comment by NXTler** [comment]
Can we get the Crashlog?

**Comment by benjiyk** [comment]
It doesn’t hand one

**Comment by benjiyk** [comment]
[crash-2021-07-22_13.42.01-server.txt](https://github.com/jediminer543/JMT-MCMT/files/6864930/crash-2021-07-22_13.42.01-server.txt)

**Comment by benjiyk** [comment]
that is the crash file above

**Comment by Sushant-Padha** [comment]
I have highlighted this problem in issue #77 

Basically, this crashes because MCMT does not even work with a Forge version higher than 36.1.36

**Comment by jediminer543** [comment]
Duplicate of #77 as said; closing
