### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KubiRem** [jediminer543/JMT-MCMT#8]
When this mod will be on 1.12.2. Does it will work with Cubic Chunks????
If no can U please do all the things that U can to make it work.
I really need cubic chunks for my modpack.
Making video about Ur mod is deleyed a bit cuz I am ill.
Best Regrads!!!
KubiRemPL

**Comment by PaintNinja** [comment]
Duplicate of https://github.com/jediminer543/JMT-MCMT/issues/2

**Comment by KubiRem** [comment]
I don't ask when 1.12.2 will come out. I ask about cubic chunks support.

**Comment by PaintNinja** [comment]
Cubic chunks is only on 1.12 and older at the moment, so no, it won't work with cubic chunks.

**Comment by KubiRem** [comment]
I mean this mod is todo for 1.12.2 and i know cubic chunks changes similar classes as this mod on 1.15.2

**Comment by KubiRem** [comment]
Closing this issue I misunderstanded something cubic chunks will not work even if this mod will be on 1.12.2.
