### ISSUE TITLE
Bug with 2560x1440 screen

### ISSUE THREAD

**Issue by ItsMeSKKYZ3R** [jediminer543/JMT-MCMT#90]
Hey! I bought a 1440p screen and I want to play Minecraft with multi-threading. But, when I launch Minecraft with **_Forge 1.16.5_** and MCMT, my 2 screens are **_restarting_** and whenever I click on Minecraft for show it, my screens are **_restarting_** and Minecraft go down.

**Comment by jediminer543** [comment]
This is possibly an external issue with a graphics driver or something, due to a lack of memory or CPU time?

Closing due to age; please reopen with logs if you want me to have a look

**Comment by ghost** [comment]
Hey, for start what a windows version do you use? Maybe i have the same problem
